### ISSUE TITLE
Not following IHE-FHIR recommendation for IG publisher use

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/DCP#1]
This GitHub repo seems to be building an IG and not using the recommendations from IHE-FHIR, thus not following IHE governance.

**Comment by brynrhodes** [comment]
What guidance is not being followed?

**Comment by JohnMoehrke** [comment]
1. IHE has a template. The build you have uses the HL7 template
2. IHE has defined conformance resource recommendations/requirements (I didn't check yours) 
 -- https://wiki.ihe.net/index.php/Guidance_on_writing_Profiles_of_FHIR 
3. not much more is well defined... so mostly I am asking for your needs. We have a team working on this next level of guidance. Welcome to join us. (this issue I logged is mostly a recruiting tool)
    https://github.com/IHE/supplement-template

**Comment by brynrhodes** [comment]
Ah, I see. Yes, this repository was created a while ago and the IHE template either didn't exist or that time or I wasn't aware of it. I was just setting up this repository to illustrate how it could be done for this project, if there's a better way now, let's do that for sure

**Comment by JohnMoehrke** [comment]
so is this an official project? Or just experimental for committee learning?

The IHE-FHIR team has not yet produced a good sample to base your stuff on. We have 4 different proposals, all in disrepair. mostly the disrepair is because of the instability of the IG and sushi build and the improvements happening there.

**Comment by brynrhodes** [comment]
I put it together as part of trying to help DCP get to a FHIR-based IG, but it kind of stalled after the initial creation of the repository. If I were to do it again today it would definitely use templates, and it might be easier just to do a complete reset with this repository, given the amount of time that has lapsed and how much progress has happened in the template-based publisher.

**Comment by JohnMoehrke** [comment]
can I join you to the IHE-FHIR workgroup?

**Comment by brynrhodes** [comment]
Yes, happy to help!

**Comment by JohnMoehrke** [comment]
Can you update the readme on this repo to indicate it is experimental? Good to also explain the reason it existed, and likely future possibilities.. Then close this issue.

**Comment by brynrhodes** [comment]
Done
